[project]
name = "firedrake"
version = "0.14"
description = "An automated system for the portable solution of partial differential equations using the finite element method"
readme = "README.rst"
license = {file = "LICENSE"}
authors = [
  {name = "The Firedrake Team", email = "firedrake@imperial.ac.uk"},
  {name = "Jack Betteridge", email = "J.Betteridge@imperial.ac.uk"},
]
maintainers = [
  {name = "The Firedrake Team", email = "firedrake@imperial.ac.uk"},
  {name = "Jack Betteridge", email = "J.Betteridge@imperial.ac.uk"},
]
dependencies = [
  "cachetools",
  "mpi4py",
  "h5py",
  "petsc4py",
  "numpy>=2.0",
  "packaging",
  "pkgconfig",
  "progress",
  "pycparser",
  "pytools",
  "requests",
  "rtree>=1.2",
  "scipy",
  "sympy",
  "fenics-ufl @ git+https://github.com/firedrakeproject/ufl.git",
  "fenics-fiat @ git+https://github.com/firedrakeproject/fiat.git",
  "finat @ git+https://github.com/FInAT/FInAT.git",
  "tsfc @ git+https://github.com/firedrakeproject/tsfc.git",
  "pyadjoint-ad @ git+https://github.com/dolfin-adjoint/pyadjoint.git",
  "loopy @ git+https://github.com/firedrakeproject/loopy.git@main",
  "libsupermesh @ git+https://github.com/firedrakeproject/libsupermesh.git@JDBetteridge/pip_install",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Operating System :: Unix",
]

[project.urls]
Homepage = "https://firedrakeproject.org"
Repository = "https://github.com/firedrakeproject/firedrake"
Issues = "https://github.com/firedrakeproject/firedrake/issues/new/choose"

[project.scripts]
firedrake-clean = "scripts.firedrake-clean:main"
firedrake-preprocess-bibtex = "scripts.firedrake-preprocess-bibtex:main"
firedrake-status = "scripts.firedrake-status:main"
pyop2-clean = "pyop2.compilation:clear_compiler_disk_cache"
spydump = "scripts.spydump:main"

[project.optional-dependencies]
test = [
  "pylit",
  "nbval",
  "pytest",
  "pytest-xdist",
  "pytest-mpi @ git+https://github.com/firedrakeproject/pytest-mpi.git@main",
]
dev = [
  "flake8",
  "pylint",
]
slepc = [
  "slepc4py",
]

[build-system]
requires = [
  "setuptools>61.2",
  "Cython>=3.0",
  "pybind11",
  "versioneer",
  "numpy>=2.0",
  "mpi4py",
  "petsc4py",
  "rtree>=1.2",
  "libsupermesh @ git+https://github.com/firedrakeproject/libsupermesh.git@JDBetteridge/pip_install",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]

[tool.versioneer]

