name: Publish on PyPI

# By default this action does not push to test or production PyPI. The wheels
# are available as an artifact that can be downloaded and tested locally.

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to publish
        default: master
        type: string
      pypi:
        description: Publish to PyPI
        default: false
        type: boolean
      test_pypi:
        description: Publish to TestPyPI
        default: false
        type: boolean

  workflow_call:
    inputs:
      ref:
        description: Git ref to publish
        default: master
        type: string
      pypi:
        description: Publish to PyPI
        default: false
        type: boolean
      test_pypi:
        description: Publish to TestPyPI
        default: false
        type: boolean

  # UNDO ME
  pull_request:

jobs:
  upload_pypi:
    name: Upload to PyPI (optional)
    # UNDO ME
    # if: github.event.inputs.pypi == 'true'
    if: false
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Push to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  upload_test_pypi:
    name: Upload to TestPyPI (optional)
    # UNDO ME
    # if: github.event.inputs.test_pypi == 'true'
    if: false
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Push to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
